name: futsal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  sqflite: ^2.3.3+1
  google_fonts: ^6.2.1
  intl: ^0.20.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

#  # مشخص کردن منابع تصویری
  assets:
    - assets/image/logo.jfif
#
#  # مشخص کردن فونت‌های سفارشی
#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: fonts/Roboto-Regular.ttf
#        - asset: fonts/Roboto-Bold.ttf
#          weight: 700
